defaults:
  - aggregator: attention
  - _self_
  - override hydra/launcher: joblib

common_settings:
  sparse: false
  n_epochs: 30
  c_mae_penalize: 0.1
  use_cv: true
  note: "Hydra Multirun"
  k_cv: 5
  seeds: [0, 37, 42]

optimizer_settings:
  init_points: 20
  n_iter: 20
  random_state: 1

hydra:
  launcher:
    n_jobs: 2
