aggregator: AttentionAggregation
pbounds:
  hidden_size: [35, 45]
  n_hidden: [1, 3.99]
  encoding_size: [20, 50.99]
  log_learning_rate: [-2, -1.99]
  log_decay: [-2.5, -1]
  attention_hidden_size: [5, 20]
